**Deep Leaning**

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
cd /content/drive/My Drive/Datasets/Others

/content/drive/My Drive/Datasets/Others


In [3]:
ls

Churn_Modelling.csv


# ANN

# Preprocessing

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
dataset.describe

<bound method NDFrame.describe of       RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...          

In [0]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [0]:
#for converting from categorical to numerical like word to number4
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [0]:
# for gender
labelEncoderGender = LabelEncoder()
X[:,2] = labelEncoderGender.fit_transform(X[:,2])

In [12]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
transformer = ColumnTransformer(
    transformers=[
        ("OneHot",        # Just a name
         OneHotEncoder(), # The transformer class
         [1]              # The column(s) to be applied on.
         )
    ],
    remainder='passthrough' # donot apply anything to the remaining columns
)
X = transformer.fit_transform(X)

In [14]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
X = X[:,1:]

In [16]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
X[:,0] = X[:,0].astype(int)
X[:,1] = X[:,1].astype(int)

In [18]:
X

array([[0, 0, 619, ..., 1, 1, 101348.88],
       [0, 1, 608, ..., 0, 1, 112542.58],
       [0, 0, 502, ..., 1, 0, 113931.57],
       ...,
       [0, 0, 709, ..., 0, 1, 42085.58],
       [1, 0, 772, ..., 1, 0, 92888.52],
       [0, 0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
#training start (spliting)
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# scaling features
from sklearn.preprocessing import StandardScaler


In [0]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# Training and tesing

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
classifier = Sequential()

In [0]:
#dense will initialize the input and hidden layer in ann
#selecting output dim is an Art , no rules of thumb, for this session - I am taking average of input and output layer  which is 11+1 / 2 = 6
#init initialized the initial weight, which we need to initialize close to Zero  with normal / uniform distribution
#in standard way, relu is good for input and sigmoid is good for output   
#input dimension is first attempt must have to be mention 
#important note is , in dense we  must declare all the necessary parameter
classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu', input_dim = 11))

In [0]:
#as first input and hidden layer is initialized with Dense()
#second hidden layer
# as I've mentioned earlier , no need  to add input_dim after first attempt , as  the system already knows about this 
classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu'))

In [0]:
#output layer
#sigmoid is  the heart of probabilistic function
#it is  a binary classification so output dim here will be = 1
#for more than binary classification , such as for 3 categories we'll need  3 output dim
#and activation will be "softmax"
classifier.add(Dense(output_dim = 1, init= 'uniform', activation = 'sigmoid'))

In [0]:
#optimization stuffs
#for backpropagations stuffs  I have used "adam" here, loss function => for binary = binary_crossentropy ->for more than two = categorical_crossentropy  (sgd)
#after each update of the weight we need  some means to evaluate the model at present situation
#so for that method funcstion come metrics= ['accuracy'] (as it demands a  list)
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [29]:
  #here we have only defined  layers but till now  no connection -> for  this fit actually comes in
  #for selecting batch_size and  epochs , there's no fixed rules 
  classifier.fit(X_train,y_train, batch_size = 10, epochs= 100)




Epoch 1/100





8000/8000 [==============================] - 13s 2ms/step - loss: 0.4811 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 4s 494us/step - loss: 0.4287 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 4s 497us/step - loss: 0.4233 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 4s 490us/step - loss: 0.4183 - acc: 0.8177
Epoch 5/100
8000/8000 [==============================] - 4s 515us/step - loss: 0.4159 - acc: 0.8250
Epoch 6/100
8000/8000 [==============================] - 4s 500us/step - loss: 0.4142 - acc: 0.8300
Epoch 7/100
8000/8000 [==============================] - 4s 470us/step - loss: 0.4123 - acc: 0.8305
Epoch 8/100
8000/8000 [==============================] - 4s 480us/step - loss: 0.4111 - acc: 0.8302
Epoch 9/100
8000/8000 [==============================] - 4s 479us/step - loss: 0.4105 - acc: 0.8316
Epoch 10/100
8000/8000 [==============================] - 4s 493us/step - loss: 0.4087 - acc:

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
#y_pred contains the probabilities , so for determining the  final decision
threshold = 0.5
y_pred = y_pred > threshold

In [0]:
from sklearn.metrics import confusion_matrix
confMat = confusion_matrix(y_test,y_pred)

In [33]:
confMat

array([[1546,   49],
       [ 267,  138]])

In [39]:
(1546+138) / 2000

0.842

In [35]:
#single evaluation point
new_evaluationPoint = np.array([[0,0,600,1,40,3,60000,2,1,1,50000]])
scaledPoint = sc.transform(new_evaluationPoint)
new_pred = classifier.predict(scaledPoint)
new_pred = new_pred > 0.5
new_pred

array([[False]])

So with ANN we have accuracy of 84% (approx) without using any tuning
And as training and testing accuracy is almost similar , so this is satisfactory 

# Optimization

In [0]:
# we have implemented  stuffs so far using keras
# but k-fold is from scikit learn
# for combining this there's a wrapper called KerasClassifier -> Keras.wrapper.scikit_learn
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [0]:
# now for building the previous classifier

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1, init= 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier


In [0]:
# for wrapping stuffs up 
# global classifier
# KerasClassifier takes Internal architecture of our own Neural Network model
# all the important stuffs are done here 
# we performing k fold to compare with the previous one and also the bias variance stuffs

global_classifier = KerasClassifier(build_fn= build_classifier, batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator= global_classifier, X = X_train, y = y_train, cv= 10, n_jobs = -1)


In [44]:
 accuracies

array([0.78625   , 0.79      , 0.80125   , 0.7825    , 0.81625   ,
       0.81      , 0.7875    , 0.79375   , 0.79875   , 0.79499999])

In [0]:
mean =  accuracies.mean()
variance = accuracies.std()   

In [48]:
print(mean," ",variance )

0.7961249969899654   0.010161968728235533


# Drop out regularization for reducing overfitting
# Parameter Tuning

In [0]:
from keras.layers import Dropout

In [0]:
#in most basic idea, this regularization disbles randomly a fraction of neuron in each iteration 
# start with the lower value of p such as 0.1 in Dropout and increase if the overfitting still occurs 

classifier = Sequential()
classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu', input_dim = 11))
classifier.Dropout(p = 0.1)

classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu'))
classifier.Dropout(p = 0.1)

classifier.add(Dense(output_dim = 1, init= 'uniform', activation = 'sigmoid'))
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 



**Parameter Tuning**

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [0]:
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(output_dim = 6, init= 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1, init= 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer= optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

**we are going to tune batch size and epochs**

In [0]:
global_classifier = KerasClassifier(build_fn= build_classifier)

In [0]:
parameters = { 'batch_size' : [25,32] , 'nb_epoch' : [100,500], 'optimizer' : ['adam', 'rmsprop']}

In [68]:
grid_search = GridSearchCV(estimator = global_classifier, param_grid = parameters, scoring = 'accuracy', cv=10)
grid_search = grid_search.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """


Epoch 1/1
7200/7200 [==============================] - 2s 234us/step - loss: 0.5644 - acc: 0.7956
Epoch 1/1
7200/7200 [==============================] - 2s 241us/step - loss: 0.5842 - acc: 0.7949
Epoch 1/1
7200/7200 [==============================] - 2s 243us/step - loss: 0.5614 - acc: 0.7954
Epoch 1/1
7200/7200 [==============================] - 2s 253us/step - loss: 0.5636 - acc: 0.7968
Epoch 1/1
7200/7200 [==============================] - 2s 265us/step - loss: 0.5672 - acc: 0.7928
Epoch 1/1
7200/7200 [==============================] - 2s 275us/step - loss: 0.5656 - acc: 0.7929
Epoch 1/1
7200/7200 [==============================] - 2s 297us/step - loss: 0.5525 - acc: 0.7951
Epoch 1/1
7200/7200 [==============================] - 2s 307us/step - loss: 0.5623 - acc: 0.7960
Epoch 1/1
7200/7200 [==============================] - 2s 291us/step - loss: 0.5504 - acc: 0.7939
Epoch 1/1
7200/7200 [==============================] - 2s 298us/step - loss: 0.5632 - acc: 0.7950
Epoch 1/1
7200/7200 

In [0]:
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

In [70]:
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}

In [71]:
best_accuracy

0.796

# CNN