In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import numpy as np 
import torch

# Matrix == Tensor in pytorch
Syntax similar to numpy

In [5]:
torch.Tensor([[1,2],[3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
torch.rand(2,2)

tensor([[0.8801, 0.7957],
        [0.9397, 0.2922]])

#   seed for reproducibility

In [8]:
#seed for same  random value
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [9]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [10]:
torch.cuda.is_available()

True

In [0]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(0)

# Torch to numpy bridge

Numpy to Torch

All can't be converted to numpy to pytorch, supported types are, double, float, int32, int16 

In [0]:
np_array = np.ones((2,2))

In [21]:
np_array

array([[1., 1.],
       [1., 1.]])

In [22]:
type(np_array)

numpy.ndarray

In [0]:
torch_example = torch.from_numpy(np_array)

In [24]:
torch_example

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [25]:
type(torch_example)

torch.Tensor

Torch to numpy

In [26]:
torch_example

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [27]:
type(torch_example)

torch.Tensor

In [0]:
torch_to_numpy = torch_example.numpy()

In [29]:
type(torch_to_numpy)

numpy.ndarray

# Tensor to CPU and GPU

In [0]:
#  by default it will be in cpu, but for faster computation we need to  transfer it to GPU
tensor_cpu = torch.ones(2,2)

In [0]:
# for transferring

if torch.cuda.is_available():
    tensor_cpu.cuda()


In [36]:
# for transferring to cpu 

tensor_cpu.cpu() 

tensor([[1., 1.],
        [1., 1.]])

# Basic Mathematical Operation

In [38]:
# resizing

tensorEx = torch.ones(2,2)
print(tensorEx)
print(tensorEx.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [41]:
# now for resizing 

tensorEx = tensorEx.view(4)

print(tensorEx)
print(tensorEx.size())

tensor([1., 1., 1., 1.])
torch.Size([4])


In [54]:
# bitwise addition

a = torch.ones(2,2)
b = torch.ones(2,2)

c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [55]:
# another  way of this  
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]])

In [56]:
# in place addition

c.add_(a)

tensor([[3., 3.],
        [3., 3.]])

In [0]:
# Element wise subtraction

c = a-b

In [58]:
torch.sub(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [59]:
#  it doesn't affect destination
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [60]:
# for in place
#  it does affect destination
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [0]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [63]:
# multiplication

a*b

tensor([[0., 0.],
        [0., 0.]])

In [64]:
torch.mul(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [67]:
# not in place
a.mul(b)

tensor([[0., 0.],
        [0., 0.]])

In [68]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [69]:
# for  in place
a.mul_(b)

tensor([[0., 0.],
        [0., 0.]])

In [70]:
print(a)
print(b)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [82]:
# division

a = torch.Tensor([[4,4],[4,4]])
b = torch.Tensor([[2,2],[2,2]])
print(a)
print(b)

tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [83]:
a/b

tensor([[2., 2.],
        [2., 2.]])

In [84]:
a.div(b)

tensor([[2., 2.],
        [2., 2.]])

In [85]:
print(a)
print(b)

tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [88]:
a.div_(b)

tensor([[2., 2.],
        [2., 2.]])

In [89]:
print(a)
print(b)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [91]:
#  for  mean
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [92]:
a.mean(dim = 0)

tensor(5.5000)

In [93]:
a.std(dim =0)

tensor(3.0277)