In [0]:
import numpy as np 
import torch

# Matrix == Tensor in pytorch
Syntax similar to numpy

In [2]:
torch.Tensor([[1,2],[3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [3]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [4]:
torch.rand(2,2)

tensor([[0.5499, 0.1920],
        [0.2792, 0.7893]])

#   seed for reproducibility

In [5]:
#seed for same  random value
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [6]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [7]:
torch.cuda.is_available()

True

In [0]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(0)

# Torch to numpy bridge

Numpy to Torch

All can't be converted to numpy to pytorch, supported types are, double, float, int32, int16 

In [0]:
np_array = np.ones((2,2))

In [10]:
np_array

array([[1., 1.],
       [1., 1.]])

In [11]:
type(np_array)

numpy.ndarray

In [0]:
torch_example = torch.from_numpy(np_array)

In [13]:
torch_example

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [14]:
type(torch_example)

torch.Tensor

Torch to numpy

In [15]:
torch_example

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [16]:
type(torch_example)

torch.Tensor

In [0]:
torch_to_numpy = torch_example.numpy()

In [18]:
type(torch_to_numpy)

numpy.ndarray

# Tensor to CPU and GPU

In [0]:
#  by default it will be in cpu, but for faster computation we need to  transfer it to GPU
tensor_cpu = torch.ones(2,2)

In [0]:
# for transferring

if torch.cuda.is_available():
    tensor_cpu.cuda()


In [21]:
# for transferring to cpu 

tensor_cpu.cpu() 

tensor([[1., 1.],
        [1., 1.]])

# Basic Mathematical Operation

In [22]:
# resizing

tensorEx = torch.ones(2,2)
print(tensorEx)
print(tensorEx.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [23]:
# now for resizing 

tensorEx = tensorEx.view(4)

print(tensorEx)
print(tensorEx.size())

tensor([1., 1., 1., 1.])
torch.Size([4])


In [24]:
# bitwise addition

a = torch.ones(2,2)
b = torch.ones(2,2)

c = a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [25]:
# another  way of this  
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]])

In [26]:
# in place addition

c.add_(a)

tensor([[3., 3.],
        [3., 3.]])

In [0]:
# Element wise subtraction

c = a-b

In [28]:
torch.sub(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [29]:
#  it doesn't affect destination
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [30]:
# for in place
#  it does affect destination
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [0]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [32]:
# multiplication

a*b

tensor([[0., 0.],
        [0., 0.]])

In [33]:
torch.mul(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [34]:
# not in place
a.mul(b)

tensor([[0., 0.],
        [0., 0.]])

In [35]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [36]:
# for  in place
a.mul_(b)

tensor([[0., 0.],
        [0., 0.]])

In [37]:
print(a)
print(b)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [38]:
# division

a = torch.Tensor([[4,4],[4,4]])
b = torch.Tensor([[2,2],[2,2]])
print(a)
print(b)

tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [39]:
a/b

tensor([[2., 2.],
        [2., 2.]])

In [40]:
a.div(b)

tensor([[2., 2.],
        [2., 2.]])

In [41]:
print(a)
print(b)

tensor([[4., 4.],
        [4., 4.]])
tensor([[2., 2.],
        [2., 2.]])


In [42]:
a.div_(b)

tensor([[2., 2.],
        [2., 2.]])

In [43]:
print(a)
print(b)

tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [44]:
#  for  mean
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [45]:
a.mean(dim = 0)

tensor(5.5000)

In [46]:
a.std(dim =0)

tensor(3.0277)

# Pytorch Variable | Gradient 

Variable

In [0]:
import torch
from torch.autograd import Variable

In [69]:
a = Variable(torch.ones(2,2), requires_grad = True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


Gradient

In [70]:
x = Variable(torch.ones(2,1),requires_grad = True)
print(x)

tensor([[1.],
        [1.]], requires_grad=True)


In [71]:
y = 5 * (x+1) ** 2
print(y)

tensor([[20.],
        [20.]], grad_fn=<MulBackward0>)


In [72]:
o = 0.5 * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [73]:
o.backward()
o

tensor(20., grad_fn=<MulBackward0>)

In [76]:
x.grad      # which is eventually the differentiation of the original equation where x is replaced by it's origin value
# that's why we needed requires_grad  = true

tensor([[10.],
        [10.]])