In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
import torch

# Matrix == Tensor in pytorch
Syntax similar to numpy

In [5]:
torch.Tensor([[1,2],[3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.rand(2,2)

tensor([[0.4827, 0.2238],
        [0.3810, 0.5355]])

#   seed for reproducibility

In [9]:
#seed for same  random value
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [11]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [12]:
torch.cuda.is_available()

True

In [0]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(0)

# Torch to numpy bridge